version: 2.1
orbs:
    node: circleci/node@5.0.2
    eb: circleci/aws-elastic-beanstalk@2.0.1
    aws-cli: circleci/aws-cli@3.1.1
jobs:
    build:
        docker:
            - image: "cimg/node:16.0.0"
        steps:
            - node/install:
                  node-version: "16.0.0"
            - checkout
            - run:
                  name: Install Front-End Dependencies
                  command: |
                      echo "NODE --version" 
                      echo $(node --version)
                      echo "NPM --version" 
                      echo $(npm --version)
                      npm run frontend:install
            # TODO: Install dependencies in the the backend API
            - run:
                  name: Install API Dependencies
                  command: |
                      npm run api:install
            # TODO: Lint the frontend
            - run:
                  name: Front-End Lint
                  command: |
                      npm run frontend:lint
            # TODO: Build the frontend app
            - run:
                  name: Front-End Build
                  command: |
                      npm run frontend:build
            # TODO: Build the backend API
            - run:
                  name: API Build
                  command: |
                      npm run api:build
    deploy:
        docker:
            - image: "cimg/base:stable"
        steps:
            - node/install:
                  node-version: "16.0.0"
            - eb/setup
            - aws-cli/setup
            - checkout
            # deploy
            - run:
                  name: Deploy
                  command: |
                      npm run deploy

workflows:
    udagram:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
